database:
  url : jdbc:postgresql://localhost:5432/Final_ProjectDB
  login : User_FP
  password : 5432
  initialSize : 10
  maxActive : 7
---
server:
  port : 8082
---
validation:
  MIN_LOAN_TYPE : 1
  MAX_LOAN_TYPE : 4
  MIN_TYPE_OF_APPLICANT : 1
  MAX_TYPE_OF_APPLICANT : 2
  MAIN_APPLICANT : 1
  MAX_AMOUNT_APPLICANTS : 5
  MIN_EXPERIENCE : 1
  MAX_EXPERIENCE : 5
  MIN_MARITAL_STATUS : 1
  MAX_MARITAL_STATUS : 3
  MIN_EDUCATION : 1
  MAX_EDUCATION : 6
---
mortgagescoring:
  MORTGAGE_INITIAL_SCORE : 0
  AGE_MORTGAGE_LESS_25_VALUE : 1
  AGE_MORTGAGE_MORE_25_LESS_40_VALUE : 10
  AGE_MORTGAGE_MORE_40_VALUE : 7
  GENDER_MORTGAGE_M_VALUE : 7
  GENDER_MORTGAGE_F_VALUE : 5
  EXPERIENCE_MORTGAGE_LESS_1M_VALUE : 1
  EXPERIENCE_MORTGAGE_MORE_1M_LESS_1Y_VALUE : 2
  EXPERIENCE_MORTGAGE_MORE_1Y_LESS_3Y_VALUE : 5
  EXPERIENCE_MORTGAGE_MORE_3Y_LESS_10Y_VALUE : 7
  EXPERIENCE_MORTGAGE_MORE_10Y_VALUE : 8
  MARITAL_STATUS_MORTGAGE_SINGLE_VALUE : 3
  MARITAL_STATUS_MORTGAGE_MARRIED_VALUE : 9
  MARITAL_STATUS_MORTGAGE_DIVORCED_VALUE : 5
  EDUCATION_MORTGAGE_HIGHER_VALUE : 8
  EDUCATION_MORTGAGE_MAGISTRACY_VALUE : 9
  EDUCATION_MORTGAGE_PHD_VALUE : 10
  EDUCATION_MORTGAGE_SECONDARY_VALUE : 2
  EDUCATION_MORTGAGE_VOCATIONAL_VALUE : 5
  EDUCATION_MORTGAGE_WITHOUT_VALUE : 1
  NO_CHILD_MORTGAGE_VALUE : 5
  ONE_CHILD_MORTGAGE_VALUE : 8
  TWO_CHILDES_MORTGAGE_VALUE : 7
  THREE_CHILDES_MORTGAGE_VALUE : 4
  DEFAULT_CHILDS_AMOUNT_MORTGAGE_VALUE : 1
  CUT_OFF_MORTGAGE : 20
---
autoscoring:
  AUTO_INITIAL_SCORE : 0
  AGE_AUTO_LESS_25_VALUE : 1
  AGE_AUTO_MORE_25_LESS_40_VALUE : 10
  AGE_AUTO_MORE_40_VALUE : 7
  GENDER_AUTO_M_VALUE : 7
  GENDER_AUTO_F_VALUE : 5
  EXPERIENCE_AUTO_LESS_1M_VALUE : 1
  EXPERIENCE_AUTO_MORE_1M_LESS_1Y_VALUE : 2
  EXPERIENCE_AUTO_MORE_1Y_LESS_3Y_VALUE : 5
  EXPERIENCE_AUTO_MORE_3Y_LESS_10Y_VALUE : 7
  EXPERIENCE_AUTO_MORE_10Y_VALUE : 8
  MARITAL_STATUS_AUTO_SINGLE_VALUE : 3
  MARITAL_STATUS_AUTO_MARRIED_VALUE : 9
  MARITAL_STATUS_AUTO_DIVORCED_VALUE : 5
  EDUCATION_AUTO_HIGHER_VALUE : 8
  EDUCATION_AUTO_MAGISTRACY_VALUE : 9
  EDUCATION_AUTO_PHD_VALUE : 10
  EDUCATION_AUTO_SECONDARY_VALUE : 2
  EDUCATION_AUTO_VOCATIONAL_VALUE : 5
  EDUCATION_AUTO_WITHOUT_VALUE : 1
  NO_CHILD_AUTO_VALUE : 5
  ONE_CHILD_AUTO_VALUE : 8
  TWO_CHILDES_AUTO_VALUE : 7
  THREE_CHILDES_AUTO_VALUE : 4
  DEFAULT_CHILDS_AMOUNT_AUTO_VALUE : 1
  CUT_OFF_AUTO : 20
---
consloanscoring:
  CONS_LOAN_INITIAL_SCORE : 0
  CONS_LOAN_GENDER_VALUE_M : 8
  CONS_LOAN_GENDER_VALUE_F : 6
  EXPERIENCE_CONS_LOAN_VALUE_LESS_1Y : 1
  EXPERIENCE_CONS_LOAN_VALUE_MORE_1Y_LESS_3Y : 5
  EXPERIENCE_CONS_LOAN_VALUE_MORE_3Y_LESS_10Y : 8
  EXPERIENCE_CONS_LOAN_VALUE_MORE_10Y : 10
  MARITAL_STATUS_CONS_LOAN_VALUE_SINGLE : 6
  MARITAL_STATUS_CONS_LOAN_VALUE_MARRIED : 8
  MARITAL_STATUS_CONS_LOAN_VALUE_DIVORCED : 4
  EDUCATION_CONS_LOAN_VALUE_MAGISTRACY : 8
  EDUCATION_CONS_LOAN_VALUE_PHD : 10
  EDUCATION_CONS_LOAN_VALUE_SECONDARY : 4
  EDUCATION_CONS_LOAN_VALUE_VOCATIONAL : 7
  EDUCATION_CONS_LOAN_VALUE_WITHOUT : 1
  CUT_OFF_CONSUMER_LOAN : 16
---
creditcardsscoring:
  CREDIT_CARD_INITIAL_SCORE : 0
  CREDIT_CARD_GENDER_VALUE_M : 8
  CREDIT_CARD_GENDER_VALUE_F : 6
  EXPERIENCE_CREDIT_CARD_VALUE_LESS_1Y : 1
  EXPERIENCE_CREDIT_CARD_VALUE_MORE_1Y_LESS_3Y : 5
  EXPERIENCE_CREDIT_CARD_VALUE_MORE_3Y_LESS_10Y : 8
  EXPERIENCE_CREDIT_CARD_VALUE_MORE_10Y : 10
  MARITAL_STATUS_CREDIT_CARD_VALUE_SINGLE : 6
  MARITAL_STATUS_CREDIT_CARD_VALUE_MARRIED : 8
  MARITAL_STATUS_CREDIT_CARD_VALUE_DIVORCED : 4
  EDUCATION_CREDIT_CARD_VALUE_MAGISTRACY : 8
  EDUCATION_CREDIT_CARD_VALUE_PHD : 10
  EDUCATION_CREDIT_CARD_VALUE_SECONDARY : 4
  EDUCATION_CREDIT_CARD_VALUE_VOCATIONAL : 7
  EDUCATION_CREDIT_CARD_VALUE_WITHOUT : 1
  CUT_OFF_CONSCREDIT_CARD : 18